[package]
name = "hotshot-qc"
description = "Quorum certificate instantiations"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ark-std = "0.4"
bincode = { version = "1.1.3" }
bitvec = { version = "1.0.1", default-features = false, features = ["alloc", "atomic", "serde"] }
ethereum-types = { version = "0.14.1", features = ["impl-serde"] }
generic-array = "0.14.7"
hotshot-types = { path = "../../types" }
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", branch = "hotshot-compat" }
jf-utils = { git = "https://github.com/espressosystems/jellyfish", branch = "hotshot-compat" }
serde = { version = "1.0.164", features = ["derive"] }
typenum = { version = "1.16.0" }

[dev-dependencies]
hotshot-stake-table = { path = "../hotshot-stake-table" }

[features]
default = ["parallel"]
std = ["ark-std/std"]
parallel = ["jf-primitives/parallel", "jf-utils/parallel"]
# TODO: (alex) what other features should I add
full-ci = ["std", "parallel"]
